common:
  disable_tqdm: true # set true when using nohup

path:
  checkpoint: "sylber"
  quantizer1: "models/sylber/quantizer1.joblib"
  quantizer2: "models/sylber/quantizer2.npy"
  segment_dir: "segments/sylber"

dataset:
  root: "data" # ${root}/LibriSpeech/train-clean-100, train-clean-360, ...
  train_file: "src/sdhubert/files/librispeech_train_10Ksubset.txt"
  dev_file: "src/sdhubert/files/librispeech_val.txt"
  test_file: "src/sdhubert/files/librispeech_test.txt"

dataloader:
  num_workers: 30

model:
  model_type: "sylber"

n_clusters:
  step1: 16384
  step2: 4096