common:
  disable_tqdm: true # set true when using nohup

path:
  checkpoint: "sylber"
  quantizer1: "models/sylber/quantizer1.joblib"
  quantizer2: "models/sylber/quantizer2.npy"
  segment_dir: "segments/sylber"
  result: "results/sylber.json"

dataset:
  root: "data" # ${root}/LibriSpeech/train-clean-100, train-clean-360, ...
  train_file: "src/sdhubert/files/librispeech_train_10Ksubset.txt"
  dev_file: "src/sdhubert/files/librispeech_val.txt"
  test_file: "src/sdhubert/files/librispeech_test.txt"
  dev_alignment: "src/sdhubert/files/librispeech_syllable_val.json"
  test_alignment: "src/sdhubert/files/librispeech_syllable_test.json"

dataloader:
  num_workers: 30

model:
  model_type: "sylber"

quantizer:
  n_clusters1: 16384
  n_clusters2: 4096
  batch_size: 10000
  verbose: 1
  compute_labels: false
  random_state: ${common.seed}
  max_no_improvement: 100
  n_init: 5
  reassignment_ratio: 0.0