common:
  disable_tqdm: true # set true when using nohup

path:
  checkpoint: "models/sylboost/SylBoost_625Hz.pth"
  quantizer1: "models/sylboost/SylBoost_625Hz_kmeans.npy"
  quantizer2: "models/sylboost/SylBoost_625Hz_agglom.npy"
  segment_dir: "segments/sylboost"
  result: "results/sylboost.json"

dataset:
  root: "data" # ${root}/LibriSpeech/train-clean-100, train-clean-360, ...
  train_file: "src/sdhubert/files/librispeech_train_10Ksubset.txt"
  dev_file: "src/sdhubert/files/librispeech_val.txt"
  test_file: "src/sdhubert/files/librispeech_test.txt"
  dev_alignment: "src/sdhubert/files/librispeech_syllable_val.json"
  test_alignment: "src/sdhubert/files/librispeech_syllable_test.json"

dataloader:
  num_workers: 30

model:
  model_type: "sylboost"
  model_key: "6.25Hz"

quantizer:
  n_clusters2: 8192

mincut:
  sec_per_frame: 0.02