common:
  disable_tqdm: true # set true when using nohup
  seed: 0

path:
  checkpoint: "models/vg-hubert_3"
  quantizer1: "models/vg-hubert_3/quantizer1.npy"
  quantizer2: "models/vg-hubert_3/quantizer2.npy"
  segment_dir: "segments/vg-hubert_3"
  result: "results/vg-hubert_3.json"

dataset:
  root: "data" # ${root}/LibriSpeech/train-clean-100, train-clean-360, ...
  download: false
  max_sample_size: 80080 # 5 seconds
  train_file: "src/sdhubert/files/librispeech_train_10Ksubset.txt"
  dev_file: "src/sdhubert/files/librispeech_val.txt"
  test_file: "src/sdhubert/files/librispeech_test.txt"
  dev_alignment: "src/sdhubert/files/librispeech_syllable_val.json"
  test_alignment: "src/sdhubert/files/librispeech_syllable_test.json"

dataloader:
  batch_size: 72 # work with single 24GB VRAM GPU
  num_workers: 30

model:
  model_type: "vghubert"
  segmentation_layer: 8

quantizer:
  n_clusters1: 16384
  n_clusters2: 4096
  niter: 100
  nredo: 5
  verbose: true
  random_state: ${common.seed}
  min_points_per_centroid: 1
  max_points_per_centroid: null

mincut:
  sec_per_frame: 0.02
  sec_per_syllable: 0.2
  merge_threshold: 0.3
  min_duration: 3
  max_duration: 35
  num_workers: 32